-- 코드를 입력하세요
SELECT FP.PRODUCT_ID , FP.PRODUCT_NAME , FO.AMOUNT * FP.PRICE
FROM FOOD_PRODUCT FP
JOIN (SELECT PRODUCT_ID , 
        SUM(AMOUNT) AMOUNT
      FROM FOOD_ORDER
      WHERE YEAR(PRODUCE_DATE) = 2022
      AND MONTH(PRODUCE_DATE) = 05
      GROUP BY PRODUCT_ID) FO
ON FO.PRODUCT_ID = FP.PRODUCT_ID
ORDER BY FP.PRICE * FO. AMOUNT DESC , PRODUCT_ID ASC