-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, AP.PT_NO, AP.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AP
JOIN PATIENT P ON P.PT_NO = AP.PT_NO
JOIN DOCTOR D ON D.DR_ID = AP.MDDR_ID
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
  AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD ASC;
