-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT
        FI.ID,
        FN.FISH_NAME,
        FI.LENGTH,
        MAX(FI.LENGTH) OVER (PARTITION BY FI.FISH_TYPE) AS MAX_LENGTH
    FROM FISH_INFO FI
    JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE = FN.FISH_TYPE
) maxed
WHERE LENGTH = MAX_LENGTH
ORDER BY ID ASC;


